### ISSUE TITLE
pip install doesn't work for any other python version than python3.8

### ISSUE THREAD

**Issue by yash4242** [ducha-aiki/pydegensac#15]
I was running 3.9.7. Tried to install pydegensac via `pip install pydegensac`, as suggested pyPI and a few other websites. Pip outputs:
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pydegensac (from versions: none)
ERROR: No matching distribution found for pydegensac
```
Tried to build from source as follows: 
```
git clone https://github.com/ducha-aiki/pydegensac
cd pydegensac-v_0.12/
sudo python3 setup.py build
```
the compilation failed after a some time. The following shows a few usual compile time messages just preceding the error messages and the error message as well:
```
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/degensac/exp_ranF.c:1604:21: warning: ‘error_threshold’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1604 |                 I = rFtH(u, inl, th, H, len, f, bufferP, buffer);
      |                     ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/bindings.cpp:297:12: note: ‘error_threshold’ was declared here
  297 |     double error_threshold, SymCheck_th;
      |            ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/degensac/exp_ranF.c:1676:21: warning: ‘FDSidx1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1676 |                     FDS1idx(u_2, f, err_laf, len,inliers, S.I);
      |                     ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/bindings.cpp:295:15: note: ‘FDSidx1’ was declared here
  295 |     FDsidxPtr FDSidx1;
      |               ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/degensac/exp_ranF.c:1646:17: warning: ‘EXFDS1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1646 |             S = exp_inFranicustom (u, len, inliers, S.I, th, errs, buffer, f, samidxBest, &iterID, inlLimit, *resids + 2*len + (iter_cnt-1)*RESIDS_M*len,EXFDS1,FDS1);
      |                 ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/bindings.cpp:294:14: note: ‘EXFDS1’ was declared here
  294 |     exFDsPtr EXFDS1;
      |              ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/degensac/exp_ranF.c:1646:17: warning: ‘FDS1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1646 |             S = exp_inFranicustom (u, len, inliers, S.I, th, errs, buffer, f, samidxBest, &iterID, inlLimit, *resids + 2*len + (iter_cnt-1)*RESIDS_M*len,EXFDS1,FDS1);
      |                 ^
/home/commander/Desktop/pydegensac-v_0.12/src/pydegensac/bindings.cpp:293:12: note: ‘FDS1’ was declared here
  293 |     FDsPtr FDS1;
      |            ^
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/pydegensac.dir/build.make:286: ../lib.linux-x86_64-3.9/pydegensac/pydegensac.cpython-39-x86_64-linux-gnu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:136: CMakeFiles/pydegensac.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2
Traceback (most recent call last):
  File "/home/commander/Desktop/pydegensac-v_0.12/setup.py", line 100, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/commander/Desktop/pydegensac-v_0.12/setup.py", line 38, in run
    self.build_extension(ext)
  File "/home/commander/Desktop/pydegensac-v_0.12/setup.py", line 68, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args,
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
```
A friend suggested to use specifically python3.8 in a venv, and `pip install pydegensac` worked.
Requesting to make it available to higher python versions also. Or maybe update the `Requirements` in the README to `python==3.8`.

**Comment by ducha-aiki** [comment]
Interesting. Which OS?

**Comment by yash4242** [comment]
Sorry, forgot to write.
I am running Pop!OS 21.04

**Comment by ducha-aiki** [comment]
Well, I have never heard of it and could not guarantee that it would work. I have only checked Ubuntu and Debian, which I have access to.

**Comment by yash4242** [comment]
It's an Ubuntu derivative, and very similar to ubuntu 21.04. Still, thanks for replying!

**Comment by ducha-aiki** [comment]
I haven't checked 21.04, I only do LTS. But I will check when have time.
In the meantime I recommend you to check latest OpenCV USAC_MAGSAC
https://ducha-aiki.github.io/wide-baseline-stereo-blog/2021/05/17/OpenCV-New-RANSACs.html

**Comment by yash4242** [comment]
Sure. I got pydegensac to work after making an environment with python3.8. Just wanted to let the maintainers and future users know that they might face such an issue and making an environment might be a solution.

**Comment by ducha-aiki** [comment]
https://github.com/ducha-aiki/pydegensac/issues/16#issuecomment-1438046032
